In [5]:
import torch
import numpy as np
torch.__version__

'1.3.0'

In [2]:
torch.tensor(1.3)

tensor(1.3000)

In [3]:
torch.FloatTensor(1)

tensor([1.4013e-45])

In [6]:
data = np.ones(2)
data

array([1., 1.])

In [7]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [8]:
data.shape

(2,)

In [11]:
torch.Size([2,3])

torch.Size([2, 3])

In [12]:
b=torch.tensor([1.1,2.2])

In [13]:
b

tensor([1.1000, 2.2000])

In [14]:
b.shape

torch.Size([2])

In [15]:
b.size()

torch.Size([2])

In [16]:
b=torch.tensor([[1.1,2.2],[3.3,4.4]])
b

tensor([[1.1000, 2.2000],
        [3.3000, 4.4000]])

In [17]:
b.shape

torch.Size([2, 2])

In [18]:
b.size()

torch.Size([2, 2])

In [19]:
b.dim()

2

In [23]:
a=torch.rand(2,2,3)

In [24]:
a

tensor([[[0.7641, 0.0249, 0.9367],
         [0.3795, 0.5541, 0.6338]],

        [[0.6801, 0.9374, 0.4915],
         [0.1936, 0.1705, 0.4180]]])

In [25]:
a.shape

torch.Size([2, 2, 3])

In [26]:
a[0]

tensor([[0.7641, 0.0249, 0.9367],
        [0.3795, 0.5541, 0.6338]])

In [27]:
a[1]

tensor([[0.6801, 0.9374, 0.4915],
        [0.1936, 0.1705, 0.4180]])

In [28]:
a[0][0]

tensor([0.7641, 0.0249, 0.9367])

In [29]:
a[0][0][0]

tensor(0.7641)

In [30]:
torch.Tensor(2,3)

tensor([[2.5226e-18, 4.2330e+21, 1.6534e+19],
        [3.0601e+32, 3.3129e-18, 7.2646e+22]])

In [31]:
torch.empty(2,3)

tensor([[1.0812e-05, 2.1456e-07, 1.3483e-05],
        [6.4901e-10, 1.7155e-07, 2.1347e-07]])

In [32]:
torch.randint(1,10,[3,3])

tensor([[3, 2, 8],
        [2, 1, 2],
        [6, 1, 4]])

In [33]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [34]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
torch.arange(10,0,-2)

tensor([10,  8,  6,  4,  2])

In [37]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [38]:
torch.linspace(1,6,steps=4)

tensor([1.0000, 2.6667, 4.3333, 6.0000])

In [39]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [43]:
a=torch.rand(2,3)
b=torch.rand(2,2)
a

tensor([[0.0335, 0.7239, 0.2995],
        [0.9804, 0.8407, 0.1524]])

In [44]:
b

tensor([[0.2501, 0.4700],
        [0.2244, 0.7614]])

In [45]:
idx=torch.randperm(2)
idx

tensor([0, 1])

In [57]:
idx=torch.randperm(2)

In [58]:
idx

tensor([1, 0])

In [59]:
a[idx]

tensor([[0.9804, 0.8407, 0.1524],
        [0.0335, 0.7239, 0.2995]])

In [60]:
b[idx]

tensor([[0.2244, 0.7614],
        [0.2501, 0.4700]])

In [61]:
a,b

(tensor([[0.0335, 0.7239, 0.2995],
         [0.9804, 0.8407, 0.1524]]), tensor([[0.2501, 0.4700],
         [0.2244, 0.7614]]))

In [62]:
a=torch.rand(4,3,28,28)

In [63]:
a[0].shape

torch.Size([3, 28, 28])

In [64]:
a[0,0].shape

torch.Size([28, 28])

In [65]:
a[0,0,2,4]

tensor(0.4611)

In [66]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [70]:
a[:2,0:,:,:26].shape

torch.Size([2, 3, 28, 26])

In [69]:
a[:2,-1:].shape

torch.Size([2, 1, 28, 28])

In [75]:
a.index_select(0,torch.tensor([0,2])).shape

torch.Size([2, 3, 28, 28])

In [76]:
a.index_select(1,torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [77]:
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [78]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [79]:
a[0,...,::2].shape

torch.Size([3, 28, 14])

In [80]:
x=torch.randn(3,4)

In [81]:
x

tensor([[ 1.5028, -0.5990, -0.2064,  0.9540],
        [ 1.1309, -1.0406,  0.9796, -0.7386],
        [ 0.4847, -0.5506, -0.1906,  0.2352]])

In [82]:
mask=x.ge(0.5)
mask

tensor([[ True, False, False,  True],
        [ True, False,  True, False],
        [False, False, False, False]])

In [83]:
torch.masked_select(x,mask)

tensor([1.5028, 0.9540, 1.1309, 0.9796])

In [84]:
torch.masked_select(x,mask).shape

torch.Size([4])

In [85]:
src=torch.tensor([[1,2,3],[4,5,6]])
torch.take(src,torch.tensor([0,2,5]))

tensor([1, 3, 6])

In [86]:
a=torch.rand(4,1,28,28)

In [87]:
a.shape

torch.Size([4, 1, 28, 28])

In [88]:
a.view(4,28*28)

tensor([[0.5238, 0.4708, 0.7418,  ..., 0.1076, 0.2876, 0.3448],
        [0.4355, 0.5229, 0.0433,  ..., 0.8318, 0.1318, 0.5035],
        [0.4084, 0.2311, 0.7863,  ..., 0.9933, 0.2884, 0.9285],
        [0.7552, 0.3056, 0.2918,  ..., 0.2752, 0.2774, 0.3321]])

In [89]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [90]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [91]:
b=a.view(4,784)

In [92]:
b

tensor([[0.5238, 0.4708, 0.7418,  ..., 0.1076, 0.2876, 0.3448],
        [0.4355, 0.5229, 0.0433,  ..., 0.8318, 0.1318, 0.5035],
        [0.4084, 0.2311, 0.7863,  ..., 0.9933, 0.2884, 0.9285],
        [0.7552, 0.3056, 0.2918,  ..., 0.2752, 0.2774, 0.3321]])

In [94]:
a.shape

torch.Size([4, 1, 28, 28])

In [95]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [96]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [97]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])